### ISSUE TITLE
Echidna fails to find a contract to analyze in certain cases

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/echidna#311]
Despite [this file](https://github.com/kupl/VeriSmart-benchmarks/blob/master/benchmarks/cve/2018-10706.sol), has a `Token` contract, Echidna cannot find it:

```
$ echidna-test benchmarks/cve/2018-10706.sol Token --config config.yaml
Analyzing contract: /home/g/Data/VeriSmart-benchmarks/benchmarks/cve/2018-10706.sol:ERC20Token
echidna-test: No bytecode found for contract "/home/g/Data/VeriSmart-benchmarks/benchmarks/cve/2018-10706.sol:ERC20Token"
```

**Comment by montyly** [comment]
What solc version are you using? The contract requires solc >=0.4.21  and < 0.5.0 (the 0.4.18 pragma is incorrect)

When using 0.4.21 I have:
```
echidna-test t.sol Token
Analyzing contract: t.sol:ERC20Token
echidna-test: No tests found in ABI
```

**Comment by ggrieco-tob** [comment]
I'm testing with solc `Version: 0.4.24+commit.e67f0147.Linux.g++`. Maybe `crytic-compile` is not correctly generating the .json file?

**Comment by montyly** [comment]
So it seems that in some cases, Echidna does not select the correct contract to fuzz.

For example in 
```solidity
contract ERC20Token{

}

contract Token{

    bool executed = false;

    function target(uint) public{
        executed = true;
    }

    function echidna_test() public returns(bool){
        require(! executed);
        return true;
    }
}
```

Running 
```
echidna-test test.sol Token
Analyzing contract: test.sol:ERC20Token
echidna-test: ABI is empty, are you sure your constructor is right?
```

Echidna takes `ERC20Token` as target, while `Token` was given. If `Token` is renamed (`AToken` for example) it works

**Comment by ggrieco-tob** [comment]
This should be fixed in #315

**Comment by PaulRBerg** [comment]
No, this is isn't fixed. When I have a contract `Foo` that imports and extends a function-less contract `BaseInvariants`, echidna fails with the following error:

> Multiple contracts found, only analyzing the first
> Analyzing contract: /home/workspace/contracts/invariants/BaseInvariants.sol:BaseInvariants
> echidna-test: ABI is empty, are you sure your constructor is right?

This is the code for `BaseInvariants`:

```solidity
pragma solidity ^0.5.16;

contract BaseInvariants  {
    address internal constant deployer = address(0x10000);
    address internal constant caller1 = address(0x20000);
}
```

**Comment by ggrieco-tob** [comment]
@PaulRBerg are you using `--contract Foo` when calling echidna?

**Comment by PaulRBerg** [comment]
Yes. But if I remember correctly, the issue happened even if I passed the contract directly.

**Comment by snd** [comment]
running into this problem as well.

```
$ echidna-test --version
Echidna 1.6.0

$ slither --version
0.7.0
```

steps to reproduce:

put code from https://etherscan.io/address/0x2eDf094dB69d6Dcd487f1B3dB9febE2eeC0dd4c5#code into `ZeroSwapToken.sol`.

```
solc use 0.6.2
slither-prop ZeroSwapToken.sol --contract ZeroSwapToken
```

manually make `PropertiesZeroSwapTokenTransferable` and `TestZeroSwapTokenTransferable` abstract.
else one gets compilation errors.

now running

```
echidna-test TestZeroSwapTokenTransferable.sol --contract TestZeroSwapTokenTransferable --config echidna_config.yaml
```
fails with
```
Analyzing contract: /home/max/trailofbits/TestZeroSwapTokenTransferable.sol:TestZeroSwapTokenTransferable
echidna-test: No bytecode found for contract "/home/max/trailofbits/TestZeroSwapTokenTransferable.sol:TestZeroSwapTokenTransferable"
```

**Comment by fang19911030** [comment]
Echidna 1.6.0

I meet a similar error.

**Comment by ggrieco-tob** [comment]
> echidna-test: No bytecode found for contract "/home/max/trailofbits/TestZeroSwapTokenTransferable.sol:TestZeroSwapTokenTransferable"

You cannot execute a contract that has no bytecode. This is not echidna fault, but the result of making contracts abstracts. @snd, if you want to test with ZeroSwap, you must give values to the arguments of the ZeroSwap constructor:

```solidity
contract ZeroSwapToken is ERC20Permit, Ownable {
    event retrieveExcessTokens(address indexed token, address indexed destination, uint256 indexed amount);
    constructor (string memory name, string memory symbol, uint256 totalSupply)
    public
    ERC20 (name, symbol) {
        _mint(msg.sender, totalSupply);
    }
``` 

Additionally, you could have `solc` errors when compiling, like this:

```
INFO:CryticCompile:Compilation warnings/errors on TestZeroSwapTokenTransferable.sol:
Internal compiler error during compilation:
/solidity/libsolidity/parsing/Parser.cpp(268): Throw in function std::pair<solidity::frontend::ContractKind, bool> solidity::frontend::Parser::parseContractKind()
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Invalid contract kind.
[solidity::util::tag_comment*] = Invalid contract kind.

ERROR:CryticCompile:Invalid solc compilation Internal compiler error during compilation:
/solidity/libsolidity/parsing/Parser.cpp(268): Throw in function std::pair<solidity::frontend::ContractKind, bool> solidity::frontend::Parser::parseContractKind()
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Invalid contract kind.
[solidity::util::tag_comment*] = Invalid contract kind.
```

**Comment by ggrieco-tob** [comment]
@paulrberg 

This works:

```solidity
contract BaseInvariants  {
    address internal constant deployer = address(0x10000);
    address internal constant caller1 = address(0x20000);
}

contract C is BaseInvariants  {
    function f() public {} 
}
```

but you need to use `--contract C`, otherwise, it will fail (there are no ABI to execute, beyond the fallback function).

In summary, we need a good test case to reproduce the issue, or will close this issue.

**Comment by ggrieco-tob** [comment]
@paulrberg can you take a look to this so we can fix it (otherwise, feel free to close the issue)?

**Comment by paulrberg** [comment]
Hey @ggrieco-tob, yes, that worked. I can't close this issue because I didn't create it myself.

**Comment by Sentient-XII** [comment]
Hi Experiencing this same issue with Echidna 2.2.1:
[2023-07-23 20:15:16.83] Compiling ./StaxExploit.sol... Done! (0.756820674s)
Multiple contracts found, only analyzing the first
Analyzing contract: /mnt/c/Users/s/Desktop/stax/Hevm.sol:IHevm
echidna: No bytecode found for contract "/mnt/c/Users/s/Desktop/stax/Hevm.sol:IHevm"

**Comment by elopez** [comment]
Hi @Sentient-XII ! If there are multiple contracts, you should specify which one to use by calling echidna with the `--contract YourContractName` flag

**Comment by Sentient-XII** [comment]
Hi @elopez , tried that, and I get "Missing: FILES" I am trying to replicate the following release tutorial:
https://blog.trailofbits.com/2023/07/21/fuzzing-on-chain-contracts-with-echidna/#comment-120491

**Comment by elopez** [comment]
adding `--contract ...` should work for that, you should be running something like `echidna ./StaxExploit.sol --config echidna-config.yaml --contract StaxExploit` for that example in the post. I'll let the team know so that they can adjust the blog post.

**Comment by Sentient-XII** [comment]
Thanks @elopez , I was placing the flag before the call of the contract. Its running now, highly appreciated!
